### ISSUE TITLE
How to train new Action(eg:raise hands)

### ISSUE THREAD

**Issue by DayDayUpDYP** [Bigtuo/YOLOv7-Pose-Bytetrack-STGCN#2]
I want to practice raising hands Action,How to train STGCN in this project.thank you

**Comment by Bigtuo** [comment]
Sorry, this project is a simple demo, only used for human behavior recognition, training new behavior recognition needs to search relevant data.




---Original---
From: ***@***.***&gt;
Date: Thu, Dec 15, 2022 14:41 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Bigtuo/YOLOv7-Pose-Bytetrack-STGCN] How to train new Action(eg:raisehands) (Issue #2)




 
I want to practice raising hands Action,How to train STGCN in this project.thank you

**Comment by DayDayUpDYP** [comment]
Thank you for your reply
